CRUD patient (#136)
* fix: mvn clean install

Other minor fixes added, as using clinicId instead of ClinicDTO. Delete is working!

* fix: injecting MatDialog

There are a couple of issues with clinic_id while creating and updating, here is the output:

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "clinic_id"; SQL statement:
insert into patients (allergies,clinic_id,dni,email,first_name,last_name1,last_name2,medical_history_id,phone_number,id) values (?,?,?,?,?,?,?,?,?,?) [23502-224]

* fix: clinicId assigned properly

CRUD working well, but idk why telephone number is not displayed. We should test the feature informally and make some minor fixes.

* fix: phone number working

There's another weird bug: when creating a new patient and the list view refreshes automatically, suddenly patients from other clinics appears at the list. When you manually refresh, it vanishes lmao.

* fix: refresh bug solved

We shouldn't had found all patients, but finding them only by active clinic id!